baseURL = 'https://wladimirtrubizin.com/'
languageCode = 'en-us'
title = "Wladimir's Notes"
theme = 'PaperMod'
enableInlineShortcodes = true
enableRobotsTXT = true

[outputs]
home = ['HTML', 'JSON', 'RSS']

[params]
description = 'A blog about technology, projects, startup insights, and freelancing'
author = 'Wladimir Trubizin'
defaultTheme = 'auto'
showtoc = true
tocopen = false
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowShareButtons = true

[params.assets]
favicon = "favicon.png"
favicon16x16 = "favicon.png"
favicon32x32 = "favicon.png"
apple_touch_icon = "favicon.png"

# Search
[params.search]
enable = true

# Utterances Comments
[params.comments]
enabled = true
system = 'utterances'

[params.utterances]
repo = "AC4G/blog"
issueTerm = "pathname"
theme = "github-light"
darkTheme = "github-dark"

# Newsletter
[params.newsletter]
email = 'wladimir'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/AC4G'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/wladimir-trubizin-44394a369'

[[params.socialIcons]]
name = 'rss'
url = 'index.xml'
